# Generated by Django 2.2.2 on 2019-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('group', models.CharField(max_length=1)),
                ('variable', models.CharField(max_length=2)),
                ('value', models.IntegerField(max_length=3)),
            ],
        ),
    ]
