# Generated by Django 2.2.2 on 2019-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
