# Generated by Django 2.2.2 on 2019-07-10 22:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20190710_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDataJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
