# Generated by Django 2.2.2 on 2019-07-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20190711_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmdata',
            old_name='group',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='farmdata',
            old_name='variable',
            new_name='y',
        ),
    ]
