# Generated by Django 2.2.2 on 2019-07-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20190719_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdata',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
